version: '3.3'
services:
  kali:
    build: .
    cap_add:
      - NET_ADMIN
    stdin_open: true
    tty: true
    ports:
      - "22"
    networks:
      - guacamoledockercompose_internal_labs
    volumes:
      - ~/script_folder_docker:/root/script_init

networks:
  guacamoledockercompose_internal_labs:
    external: true
